### ISSUE TITLE
Polls broke dashboard?

### ISSUE THREAD

**Issue by maffiou** [humhub/humhub-modules-polls#16]
I installed the poll module and created a poll, it seems after that the dashboard is stuck on loading forever. Browsing the actual space where the poll is is fine... 

Any idea what I can do to confirm this bug? How to generate logs and stuff?

**Comment by andystrobel** [comment]
It should be fixed now. Can you please test it again?

**Comment by maffiou** [comment]
Hi Andy, 
I can't see a new version through the module UI in the admin menu nor any new commits on the github... 
Can you advise on how to test?
Thanks
