### ISSUE TITLE
Suggestion : Make Polls editable

### ISSUE THREAD

**Issue by wikibit** [humhub/humhub-modules-polls#17]
It would be a big improvement, if polls could be editable;
maybe only as long as there are no votes yet
- the title/question
- the title of each answer
- add/delete answers

**Comment by Nailuj2000** [comment]
+1

**Comment by programguy** [comment]
+1

**Comment by otdftr** [comment]
+1
and/or to copy the provided answers to a new poll - cf. https://github.com/humhub/humhub-modules-polls/issues/22

**Comment by paulooliveira** [comment]
Hi all,
Why is this closed, it's a very good feature

Tnx

**Comment by luke-** [comment]
It's possible to edit polls in the latest verison.

**Comment by paulooliveira** [comment]
> It's possible to edit polls in the latest verison.

Oh, I didn't knew that... we are using the 1.3.18 stable and were not aware of that, tnx for the reply! 👍 👍
