### ISSUE TITLE
Suggestion : Make multiple answer polls

### ISSUE THREAD

**Issue by wikibit** [humhub/humhub-modules-polls#18]
At the moment, there is only one answer possible
it would be a very nice feature, to have a "checkbox" type of poll; where users can select multiple answers.

e.g.
Poll question : "check all answers you agree with"

**Comment by luke-** [comment]
This checkbox already exists

![image](https://cloud.githubusercontent.com/assets/4736168/8822158/c350b1ce-3063-11e5-98bb-9acc62d90389.png)

**Comment by wikibit** [comment]
so it was that one ...
Interesting, that did not work in firefox, but it did in chrome
(and it works in IE also... strange)
