### ISSUE TITLE
Improper display of the votes in the poll module

### ISSUE THREAD

**Issue by daglex** [humhub/humhub-modules-polls#19]
When you view the vote of one embodiment of the survey also shows voters of the other options. I think it should not be. In the illustrated screenshot I chose the view of one embodiment of the vote, but why has issued all voters from other polling options too.

![polls](https://cloud.githubusercontent.com/assets/7894606/10551585/74db7736-7456-11e5-8699-e091bfd91020.png)

**Comment by tobciu** [comment]
https://github.com/humhub/humhub-modules-polls/pull/20 ;-)
