### ISSUE TITLE
Suggestion: Anonymous Polls and Activity List

### ISSUE THREAD

**Issue by neighlyd** [humhub/humhub-modules-polls#25]
Hello,

It seems that when Polls are set to anonymous, the activity list is still updated that they have voted. This makes it quite simple to tell who voted for what.

Does anyone know if there is a way to prevent anonymous polls from updated the Activity List?
If not, is this a feature that could be implemented?

Thank you!

**Comment by SthPhoenix** [comment]
+1 noticed this behaviour too, actually this brokes the idea of anonymous polls

**Comment by buddha87** [comment]
Thanks for noting, a new version is available which should fix this issue.

**Comment by neighlyd** [comment]
Excellent! Thank you for the quick response and fix.

Do you happen to know how long it will take for the change to propagate to the Humhub module updater, or is that a separate issue?

**Comment by buddha87** [comment]
should already be available version 0.9.0
