### ISSUE TITLE
Exception Poll Module

### ISSUE THREAD

**Issue by wlma** [humhub/humhub-modules-polls#27]
Hi everybody,
I'm getting this error, looks like its  poll related

`exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: humhub\modules\space\models\Space::permissionManager' in /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/Component.php:143 Stack trace: #0 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(247): yii\base\Component->__get('permissionManag...') #1 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/modules/polls/widgets/WallCreateForm.php(28): yii\db\BaseActiveRecord->__get('permissionManag...') #2 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/Widget.php(98): humhub\modules\polls\widgets\WallCreateForm->run() #3 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/modules/polls/views/poll/show.php(6): yii\base\Widget::widget(Array) #4 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/htdocs...') #5 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/htdocs...', Array) #6 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/htdocs...', Array, Object(humhub\modules\polls\controllers\PollController)) #7 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/Controller.php(371): yii\base\View->render('show', Array, Object(humhub\modules\polls\controllers\PollController)) #8 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/modules/polls/controllers/PollController.php(42): yii\base\Controller->render('show', Array) #9 [internal function]: humhub\modules\polls\controllers\PollController->actionShow() #10 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #11 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array) #12 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('show', Array) #13 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('polls/poll/show', Array) #14 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #15 /var/www/htdocs/wuapaa/expertenblog.raiffeisen.tirol/index.php(25): yii\base\Application->run() #16 {main} `

I'm on Humhub 0.20.1 with Polls Module 0.9.0; 

Any hint on fixing this? (Best without updating the whole Site)

**Comment by buddha87** [comment]
Version 0.20 is not supported anymore, I would suggest to update your installation and don't forget to make a backup.

**Comment by wlma** [comment]
Ok, thanks for your input, i´ll try to upgrade my installation. 
Closing this issue for now.

**Comment by wlma** [comment]
For the records: after updating no problems with this anymore.
