### ISSUE TITLE
can't activate module in a space

### ISSUE THREAD

**Issue by niconacre** [humhub/humhub-modules-polls#34]
Since last HH 1.2 update, impossible to activate module in any space, while module is activate and up to date in admin pannel.

![selection_357](https://cloud.githubusercontent.com/assets/20636666/26222874/e2661d5e-3c1b-11e7-9f5f-fbf3c54aee95.png)

**Comment by buddh4** [comment]
Flush your cache "Administration -> Settigns -> Advanced -> Cache"

**Comment by niconacre** [comment]
thx a lot !
