### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by deltatask1** [humhub/humhub-modules-polls#44]
I recently updated to latest HumHub version and now polls are not working. I've deleted the module and did a manual install and I'm getting the same result. When I click on the Poll button in any space I get "An Internal server error occurred. "

**Comment by buddh4** [comment]
Please add the actual error information "Administration -> Information -> Logging"

**Comment by deltatask1** [comment]
$_GET = [ 'r' => 'polls/poll/show' 'sguid' => '3b5586d8-56c1-4545-9402-6649cdaf8618' ] $_SERVER = [ 'PATH' => '/bin:/usr/bin:/usr/local/bin' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9' 'HTTP_COOKIE' => 'language=23268c8eda30f771c97451248cd61e7621459f2224a99fb4c5f3e3cee661d0c4a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _identity=6dce17067ed1b1973ef353eb017653c73f78218e4b691026f5e2d2ab5af5f67ca%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22d1fa54e6-82e5-4102-a91f-efad8b15b6ad%22%2C2592000%5D%22%3B%7D; _csrf=c375e346d750ec2e196a5eccea8a059d734d46cb3dfa644c25c98c482813e811a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22Z%7D%F3z%13Z%D7%9C%DAl%C6%60%88p%D2m%CF%14%D5%B6%E8%97D%A2%A8%1F%B7%22%DAI%FC%9D%22%3B%7D; pm_calendar-upcoming-events-snippet=expanded; pm_task-my-tasks-snippet=expanded; pm_panel-visitors=expanded; pm_online-users-panel=expanded; TS016f84ea=01f0e93131398ba1df48eba1b7bf2cb7be635c93d8aaf0f5e1cf0512b7a24305c78881e2456232ecead41b9180b3b60fa23861111f; pm_space-members-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-follower-panel=expanded; pm_profile-following-panel=expanded; pm_profile-friends-panel=expanded; PHPSESSID=qcequ3shoklnbvfcsda4f8j715; pm_space-gallery-snippet=expanded; cookieconsent_status=dismiss' 'HTTP_HOST' => 'forum.thethreepercenters.org' 'HTTP_REFERER' => 'https://forum.thethreepercenters.org/index.php?r=space%2Fspace&sguid=3b5586d8-56c1-4545-9402-6649cdaf8618' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'DOCUMENT_ROOT' => '/home/forumthe/public_html' 'REMOTE_ADDR' => '73.2.208.88' 'REMOTE_PORT' => '57996' 'SERVER_ADDR' => '68.66.214.83' 'SERVER_NAME' => 'forum.thethreepercenters.org' 'SERVER_ADMIN' => 'webmaster@forum.thethreepercenters.org' 'SERVER_PORT' => '443' 'REQUEST_URI' => '/index.php?r=polls%2Fpoll%2Fshow&sguid=3b5586d8-56c1-4545-9402-6649cdaf8618' 'HTTPS' => 'on' 'X_SPDY' => 'QUIC' 'SSL_PROTOCOL' => 'QUIC' 'SSL_CIPHER' => 'aes-128-gcm' 'SSL_CIPHER_USEKEYSIZE' => '128' 'SSL_CIPHER_ALGKEYSIZE' => '128' 'SCRIPT_FILENAME' => '/home/forumthe/public_html/index.php' 'QUERY_STRING' => 'r=polls%2Fpoll%2Fshow&sguid=3b5586d8-56c1-4545-9402-6649cdaf8618' 'SCRIPT_URI' => 'https://forum.thethreepercenters.org/index.php' 'SCRIPT_URL' => '/index.php' 'SCRIPT_NAME' => '/index.php' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'SERVER_SOFTWARE' => 'LiteSpeed' 'REQUEST_METHOD' => 'GET' 'X-LSCACHE' => 'on' 'PHP_SELF' => '/inde
