### ISSUE TITLE
When you close a poll, the results disappear.

### ISSUE THREAD

**Issue by rafawrm** [humhub/humhub-modules-polls#48]
After you create and close a poll, the result and answer options disappear. I saved the log below, which seems to be generated when the poll is created.
And if I create a poll with the hidden result until closing, I can not see the users who have chosen each option.

Humhub : 1.3.0-beta.2
Poll Module: 0.9.14

`exception 'yii\base\ErrorException' with message 'Creating default object from empty value' in /var/www/html/intranet/protected/modules/polls/controllers/PollController.php:128 Stack trace: #0 /var/www/html/intranet/protected/modules/polls/controllers/PollController.php(128): yii\base\ErrorHandler->handleError(2, 'Creating defaul...', '/var/www/html/i...', 128, Array) #1 /var/www/html/intranet/protected/modules/polls/controllers/PollController.php(115): humhub\modules\polls\controllers\PollController->setClosed('6', false) #2 [internal function]: humhub\modules\polls\controllers\PollController->actionOpen() #3 /var/www/html/intranet/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #4 /var/www/html/intranet/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #5 /var/www/html/intranet/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('open', Array) #6 /var/www/html/intranet/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('polls/poll/open', Array) #7 /var/www/html/intranet/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #8 /var/www/html/intranet/index.php(25): yii\base\Application->run() #9 {main} `

**Comment by niconacre** [comment]
I've got the same issue, independently of the type of pool created (multiple choice or not)

**Comment by psychicpancake** [comment]
I have also replicated the issue, which is frustrating because our user base relies on this public polling. +1

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-modules-polls/commit/3301776844de5d31810caf258ccf3bdb4c4b27a4
