### ISSUE TITLE
Add new RichText editor

### ISSUE THREAD

**Issue by navpab** [humhub/humhub-modules-polls#56]
It would be really helpful to be able to make polls stand out more by having standard text enhancement functions (bold, italics, underscore, letter sizing) as well as the ability to embed an image in the 'question' (I notice that tube videos appear as thumbnails but not HTML images). 

Is there any way to do this? :)

**Comment by luke-** [comment]
We need to migrate to the new RichText editor here.

**Comment by navpab** [comment]
Ah, good thinking, Luke! 

Is it possible?
