### ISSUE TITLE
Wall Stream Layout Migration - HumHub 1.7

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-polls#71]

**Comment by yurabakhtin** [comment]
<img width="763" alt="preview_module_polls" src="https://user-images.githubusercontent.com/6995524/96441266-ed4e2e80-1211-11eb-8821-b0cc9ffe38ff.png">

**Comment by luke-** [comment]
Currently we only have one field for the question.
With the new version we should introduce two fields here. One for the question (title) and one (optional) for a description (rich text). 

@buddh4 What do you think?

**Comment by buddh4** [comment]
Hmm, how to migrate old polls?

**Comment by luke-** [comment]
With the title in the new Wall Stream layout we have a problem at this position anyway.

Option 1:
- The existing `title/question` field becomes the `Description` with enabled richtext elements
- The new `title/question` defaults to "Poll" if empty

Option 2:
- Remove richtext elements from existing `title/question` field and show as `title`
- The new `Description` is empty as default

**Comment by buddh4** [comment]
I kind of prefer the first option. Richtext previews are often not very pretty.

**Comment by luke-** [comment]
Yes, lets proceed with the first option.
Screenshots here: https://github.com/humhub/tasks/issues/1#issuecomment-712392699

@yurabakhtin Can you also add this change.

- Rename `question` to `description`. Make to `Richtext` field.
- Create new text only `question` or `title` attribute.

On the wall stream entries, Display `Poll` when not `title/question` is set.

**Comment by buddh4** [comment]
@luke- its already a richtext field.

**Comment by yurabakhtin** [comment]
@luke- Ok, I will implement this. 
> On the wall stream entries, Display `Poll` when not `title/question` is set.

It seems you wanted to write here `description` instead of `title/question`.

> Create new text only `question` or `title` attribute.
I think to use `question` in order to don't catch unexpected error of undefined attribute `question` in some old code.

**Comment by luke-** [comment]
> On the wall stream entries, Display Poll when not title/question is set.

I meant that in terms of backward compatibility. Current Polls only have one `question` attribute which is also a rich text field.
With the new layout, the title cannot be a rich text field.

So for polls that were already created before the modification, I would simply use the word "Poll" as title and move the question to the description. 

I hope I could clarify it.

**Comment by yurabakhtin** [comment]
@luke- Yes, now I have understood we should display a static word "Poll" for wall entry title instead of reachtext when new attribute `title/question` is empty, thank you for this explanation.

**Comment by luke-** [comment]
@yurabakhtin Yes! ;-)

**Comment by yurabakhtin** [comment]
@luke- @buddh4 In previous version we displayed richtext on creating new poll, should we keep this there? Or maybe enough to display simple/string text of new `title/question` attribute, please see screenshot below for more details:
<img width="964" alt="new_poll_questions" src="https://user-images.githubusercontent.com/6995524/96596000-eb10d080-12f4-11eb-81da-42954333f150.png">

**Comment by buddh4** [comment]
Question should be simple text, no richtext. I'd like it to be required, but it should not block saving old instances. Maybe we could only require the question when creating new polls?

**Comment by yurabakhtin** [comment]
On creating:
- Display "Question"(simple text), make it required,
- Hide "Description"(richtext).
On editing:
- make "Question"(simple text) not required,
- make "Description"(richtext) NOT required (in previous version this attribute was required).

Correct me please if something is wrong.

**Comment by buddh4** [comment]
The "Description" should always be editable and visible. In the description you can add further details, or attach images/files etc.

In order to keep it simple I think we should make "Question" not required. What do you think @luke- . I just want to prevent scenarios in which the poll can not be saved due to a failed question validation.

**Comment by yurabakhtin** [comment]
@luke- @buddh4 Please check how it works in commit https://github.com/humhub/humhub-modules-polls/pull/74/commits/2e6a345fb0d0ac3a4d3e7b6fbc080d5d4d3eaf7c:

On creating:

- "Question"(simple text), Not required, Visible only after click on "Description"
- "Description"(richtext), Required, Always visible

On editing:

- "Question"(simple text), Not required
- "Description"(richtext), Required
