### ISSUE TITLE
Exclude from Mail Summary (Activity) 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-polls#80]
It is not possible to exclude Polls activities from the Mail Summary:![image](https://user-images.githubusercontent.com/4736168/106150242-6ba85e00-617b-11eb-8bd6-cc1aba8073a7.png)

https://github.com/humhub/humhub-modules-polls/blob/master/activities/NewVote.php

Especially on larger installations, this creates a lot of content in the mail summary.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-modules-polls/pull/81:
<img width="852" alt="poll_activity_setting" src="https://user-images.githubusercontent.com/6995524/106890549-868a4d80-66fa-11eb-806d-7eb846a77be9.png">
